<div id="am-revisions-panel" class="panel panel-default">
    <div class="panel-heading">
        <img src="<?= $block->getViewFileUrl('Kahanit_AweMenu/images/revisions-icon.png'); ?>"/> <span>Revisions</span>
    </div>
    <div class="panel-body">
        <!-- revisions list -->
        <div id="am-revisions">
            <table id="am-revisions-table" class="table table-hover fancytree-container fancytree-ext-table fancytree-ext-glyph">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Title</th>
                    <th>Date</th>
                    <th>Actions</th>
                </tr>
                </thead>
            </table>
        </div>
    </div>
</div>