<?php/** * CedCommerce * * NOTICE OF LICENSE * * This source file is subject to the Open Software License (OSL 3.0) * that is bundled with this package in the file LICENSE.txt. * It is also available through the world-wide-web at this URL:  * http://opensource.org/licenses/osl-3.0.php * * @category    Ced * @package     Ced_SocialLogin * @author 		CedCommerce Magento Core Team <Ced_MagentoCoreTeam@cedcommerce.com> * @copyright   Copyright CedCommerce (http://cedcommerce.com/) * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0) *//** * @category   	Ced * @package    	Ced_SocialLogin * @author		CedCommerce Magento Core Team <Ced_MagentoCoreTeam@cedcommerce.com> */?><div class="ced-sociallogin-container ced-sociallogin-container-checkout">
    <?php if($this->_currentBlock->facebookEnabled()): ?>
    <div class="ced-sociallogin-login-facebook">
        <h3><?php echo __('Facebook Connect') ?></h3>
        <p><?php echo __('You can continue using your <strong>Facebook</strong> account.') ?></p>
        <?php echo $this->getChildHtml('ced_sociallogin_checkout_facebook_button'); ?>
    </div>
    <?php endif; ?>
</div>