<?php $_helper = $this->helper('Emosys\Chat\Helper\Data') ?>

<?php if ( $_helper->getKey() ) : ?>
<!--Start of Zopim Live Chat Script by Emosys.com-->
<script type="text/javascript">
window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
_.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute("charset","utf-8");
$.src="//v2.zopim.com/?<?php echo $_helper->getKey() ?>";z.t=+new Date;$.
type="text/javascript";e.parentNode.insertBefore($,e)})(document,"script");
</script>
<!--End of Zopim Live Chat Script by Emosys.com-->

<script>
$zopim(function() {
    <?php echo $_helper->getLanguage() ?>
});
</script>
<?php else: ?>
<!-- Zopim Widget by Emosys.com is missing because the key is not defined -->
<?php endif ?>