<?php
/**
 * @author Emosys team
 * @copyright Copyright (c) 2016 Emosys Ltd (http://www.emosys.com)
 * @package Emosys_Banner
 */
?>
<?php $item = $this->getItem() ?>
<?php if ( $item->getId() ) : ?>
    <?php 
    $suffix = md5(mt_rand() . time()); 
    $collection = $item->getPhotoCollection();
    ?>
    <?php if ( count($collection) ) : ?>
    <div class="emosys-slider devrama-slider-wrapper">
        <div class="devrama-slider devrama-slider-<?php echo $suffix; ?>">
            <?php foreach ($collection as $_photo) : ?>
                <div class="d-slider-item">
                    <img data-lazy-src="<?php echo $_photo->getSrc() ?>" />
                </div>
            <?php endforeach ?>
        </div>
    </div>
    <script type="text/javascript">
    require(['jquery','Emosys_Banner/js/devrama.slider'],function($){
        $('.devrama-slider-<?php echo $suffix; ?>').DrSlider();
    });
    </script>
    <?php endif ?>
<?php endif ?>
