<?php $settingsForColor = $this->getSocialIconsColor();
$socialIconsColor = json_decode($settingsForColor, true);
?>

<?php if ($this->getEnable()): ?>
    <div class="iwd-newsletterpopup-main-wrapper" style="display: none">
        <div id="iwd-newsletterpopup-wrapper">
            <div class="main-newsletter-wrapper popup-loader">
                <div class="newsletterpopup-top subscribe-content-wrapper">
                    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('newsletter_popup')->toHtml(); ?>
                </div>
            </div>

        </div>
    </div>
<?php endif; ?>

<style>
    .iwd-newsletter-wrapper > .modal-inner-wrap {
        width: <?php echo $this->getPopupWidth().'px';?>;
        margin-top: <?php echo $this->getPopupTopPosition().'px'; ?>;
    }

    #iwd-newsletterpopup-wrapper .iwd-newsletter-send-button {
        background-color: <?php echo '#'.$this->getButtonColor();?>;
        color: <?php echo '#'.$this->getButtonTextColor();?>;
    }

    #iwd-newsletterpopup-wrapper .iwd-newsletter-send-button:hover {
        background-color: <?php echo '#'.$this->getButtonHoverColor();?>;
        color: <?php echo '#'.$this->getButtonHoverTextColor();?>;
    }



    /*STYLES FOR ICONS*/
    .iwd-newsletter-main-footer .social_links a.facebook span.fa-square{color: <?php echo '#'.$socialIconsColor['facebook_bg'];?>;}
    .iwd-newsletter-main-footer .social_links a.facebook span.fa-stack-20{color:<?php echo '#'.$socialIconsColor['facebook_icon'];?>;}
    .iwd-newsletter-main-footer .social_links a.facebook span:hover .fa-square{color:<?php echo '#'.$socialIconsColor['facebook_bg_hover'];?>;}
    .iwd-newsletter-main-footer .social_links a.facebook span.fa-stack-20:hover{color:<?php echo '#'.$socialIconsColor['facebook_icon_hover'];?>;}

    .iwd-newsletter-main-footer .social_links a.twitter span.fa-square{color:<?php echo '#'.$socialIconsColor['twitter_icon_background'];?>;}
    .iwd-newsletter-main-footer .social_links a.twitter span.fa-stack-20{color:<?php echo '#'.$socialIconsColor['twitter_icon_color'];?>;}
    .iwd-newsletter-main-footer .social_links a.twitter span:hover .fa-square{color:<?php echo '#'.$socialIconsColor['twitter_icon_hover_background'];?>;}
    .iwd-newsletter-main-footer .social_links a.twitter span.fa-stack-20:hover{color:<?php echo '#'.$socialIconsColor['twitter_icon_hover_color'];?>;}

    .iwd-newsletter-main-footer .social_links a.linkedin span.fa-square{color:<?php echo '#'.$socialIconsColor['linkedIn_icon_background'];?>;}
    .iwd-newsletter-main-footer .social_links a.linkedin span.fa-stack-20{color:<?php echo '#'.$socialIconsColor['linkedin_icon_color'];?>;}
    .iwd-newsletter-main-footer .social_links a.linkedin span:hover .fa-square{color:<?php echo '#'.$socialIconsColor['linkedin_icon_hover_background'];?>;}
    .iwd-newsletter-main-footer .social_links a.linkedin span.fa-stack-20:hover{color:<?php echo '#'.$socialIconsColor['linkedin_icon_hover_color'];?>;}

    .iwd-newsletter-main-footer .social_links a.google span.fa-square{color:<?php echo '#'.$socialIconsColor['google_icon_background'];?>;}
    .iwd-newsletter-main-footer .social_links a.google span.fa-stack-20{color:<?php echo '#'.$socialIconsColor['google_icon_color'];?>;}
    .iwd-newsletter-main-footer .social_links a.google span:hover .fa-square{color:<?php echo '#'.$socialIconsColor['google_icon_hover_background'];?>;}
    .iwd-newsletter-main-footer .social_links a.google span.fa-stack-20:hover{color:<?php echo '#'.$socialIconsColor['google_icon_hover_color'];?>;}

    .iwd-newsletter-main-footer .social_links a.youtube span.fa-square{color:<?php echo '#'.$socialIconsColor['youtube_icon_background'];?>;}
    .iwd-newsletter-main-footer .social_links a.youtube span.fa-stack-20{color:<?php echo '#'.$socialIconsColor['youtube_icon_color'];?>;}
    .iwd-newsletter-main-footer .social_links a.youtube span:hover .fa-square{color:<?php echo '#'.$socialIconsColor['youtube_icon_hover_background'];?>;}
    .iwd-newsletter-main-footer .social_links a.youtube span.fa-stack-20:hover{color:<?php echo '#'.$socialIconsColor['youtube_icon_hover_color'];?>;}

    .iwd-newsletter-main-footer .social_links a.flickr span.fa-square{color:<?php echo '#'.$socialIconsColor['flickr_icon_background'];?>;}
    .iwd-newsletter-main-footer .social_links a.flickr span.fa-stack-20{color:<?php echo '#'.$socialIconsColor['flickr_icon_color'];?>;}
    .iwd-newsletter-main-footer .social_links a.flickr span:hover .fa-square{color:<?php echo '#'.$socialIconsColor['flickr_icon_hover_background'];?>;}
    .iwd-newsletter-main-footer .social_links a.flickr span.fa-stack-20:hover{color:<?php echo '#'.$socialIconsColor['flickr_icon_hover_color'];?>;}

    .iwd-newsletter-main-footer .social_links a.vimeo span.fa-square{color:<?php echo '#'.$socialIconsColor['vimeo_icon_background'];?>;}
    .iwd-newsletter-main-footer .social_links a.vimeo span.fa-stack-20{color:<?php echo '#'.$socialIconsColor['vimeo_icon_color'];?>;}
    .iwd-newsletter-main-footer .social_links a.vimeo span:hover .fa-square{color:<?php echo '#'.$socialIconsColor['vimeo_icon_hover_background'];?>;}
    .iwd-newsletter-main-footer .social_links a.vimeo span.fa-stack-20:hover{color:<?php echo '#'.$socialIconsColor['vimeo_icon_hover_color'];?>;}

    .iwd-newsletter-main-footer .social_links a.pinterest span.fa-square{color:<?php echo '#'.$socialIconsColor['pinterest_icon_background'];?>;}
    .iwd-newsletter-main-footer .social_links a.pinterest span.fa-stack-20{color:<?php echo '#'.$socialIconsColor['pinterest_icon_color'];?>;}
    .iwd-newsletter-main-footer .social_links a.pinterest span:hover .fa-square{color:<?php echo '#'.$socialIconsColor['pinterest_icon_hover_background'];?>;}
    .iwd-newsletter-main-footer .social_links a.pinterest span.fa-stack-20:hover{color:<?php echo '#'.$socialIconsColor['pinterest_icon_hover_color'];?>;}

    .iwd-newsletter-main-footer .social_links a.instagram span.fa-square{color:<?php echo '#'.$socialIconsColor['instagram_icon_background'];?>;}
    .iwd-newsletter-main-footer .social_links a.instagram span.fa-stack-20{color:<?php echo '#'.$socialIconsColor['instagram_icon_color'];?>;}
    .iwd-newsletter-main-footer .social_links a.instagram span:hover .fa-square{color:<?php echo '#'.$socialIconsColor['instagram_icon_hover_background'];?>;}
    .iwd-newsletter-main-footer .social_links a.instagram span.fa-stack-20:hover{color:<?php echo '#'.$socialIconsColor['instagram_icon_hover_color'];?>;}

    .iwd-newsletter-main-footer .social_links a.foursquare span.fa-square{color:<?php echo '#'.$socialIconsColor['foursquare_icon_background'];?>;}
    .iwd-newsletter-main-footer .social_links a.foursquare span.fa-stack-20{color:<?php echo '#'.$socialIconsColor['foursquare_icon_color'];?>;}
    .iwd-newsletter-main-footer .social_links a.foursquare span:hover .fa-square{color:<?php echo '#'.$socialIconsColor['foursquare_icon_hover_background'];?>;}
    .iwd-newsletter-main-footer .social_links a.foursquare span.fa-stack-20:hover{color:<?php echo '#'.$socialIconsColor['foursquare_icon_hover_color'];?>;}

    .iwd-newsletter-main-footer .social_links a.tumblr span.fa-square{color:<?php echo '#'.$socialIconsColor['tumblr_icon_background'];?>;}
    .iwd-newsletter-main-footer .social_links a.tumblr span.fa-stack-20{color:<?php echo '#'.$socialIconsColor['tumblr_icon_color'];?>;}
    .iwd-newsletter-main-footer .social_links a.tumblr span:hover .fa-square{color:<?php echo '#'.$socialIconsColor['tumblr_icon_hover_background'];?>;}
    .iwd-newsletter-main-footer .social_links a.tumblr span.fa-stack-20:hover{color:<?php echo '#'.$socialIconsColor['tumblr_icon_hover_color'];?>;}

    .iwd-newsletter-main-footer .social_links a.rss span.fa-square{color:<?php echo '#'.$socialIconsColor['rss_icon_background'];?>;}
    .iwd-newsletter-main-footer .social_links a.rss span.fa-stack-20{color:<?php echo '#'.$socialIconsColor['rss_icon_color'];?>;}
    .iwd-newsletter-main-footer .social_links a.rss span:hover .fa-square{color:<?php echo '#'.$socialIconsColor['rss_icon_hover_background'];?>;}
    .iwd-newsletter-main-footer .social_links a.rss span.fa-stack-20:hover{color:<?php echo '#'.$socialIconsColor['rss_icon_hover_color'];?>;}
    /*****************/

</style>

<script>
    // <![CDATA[
    var iwdNewspopupConfig = '<?php echo $this->getPopupParams()?>';
    require(['IWD_NewsletterPopup/js/iwd_newsletterpopup'],
        function (iwdNewsletterpopup) {
            var newsletterPopup = new iwdNewsletterpopup();
            newsletterPopup.init();
            jQuery(document).on('click','.main-newsletter-wrapper .btn-thanks',function(event) {
                jQuery('.action-close').click();
            });
        });
    // ]]>
</script>
