<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Amasty_Xnotif
 */
?>
<?php /*echo $this->getMessagesBlock()->getGroupedHtml();  */ ?>
<?php $_orders = $this->getSubscriptions(); ?>
<?php echo $this->getPagerHtml(); ?>
<?php if ($_orders->getSize()): ?>

    <table class="data-table" id="my-subscriptions-table">
        <thead>
        <tr>
            <th width="50"><?php echo __('Image') ?></th>
            <th><?php echo __('Product') ?></th>
            <th><?php echo __('Subscribed On') ?></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($_orders as $_order): ?>
            <?php $_product = $this->getProduct($_order->getEntityId());
            $image = $this->_objectManager->get('Magento\Catalog\Helper\Image')->init($_product, 'small_image')->resize(45);
            if ($this->_scopeConfig->isSetFlag('amxnotif/general/account_image')) {
                $parentIds = $this->_objectManager->get('Magento\ConfigurableProduct\Model\Product\Type\Configurable')->getParentIdsByChild($_product->getId());
                if (isset($parentIds[0])) {
                    $parent = $this->_objectManager->get('Magento\Catalog\Model\Product')->load($parentIds[0]);
                    $image = $this->_objectManager->get('Magento\Catalog\Helper\Image')->init($parent, 'small_image')->resize(45);
                }
            }
            ?>
            <tr>
                <td>
                    <a href="<?php echo $this->getUrlProduct($_product) ?>">
                        <img src="<?php echo $image ?>" width="45" height="45"/>
                    </a>
                </td>
                <td>
                    <a href="<?php echo $this->getUrlProduct($_product) ?>">
                        <?php echo $_order->getName() ?>
                    </a>
                </td>
                <td><span class="nobr"><?php echo $this->formatDate($_order->getAddDate()) ?></span></td>
                <td>
                    <a href="<?php echo $this->getRemoveUrl($_order) ?>" title="<?php echo __('Remove This Item') ?>"
                       onclick="return confirm('<?php echo __('Are you sure you would like to remove this item from the subscriptions?') ?>');"
                       class="btn-remove btn-remove2"><?php echo __('Remove This Item') ?></a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <?php echo $this->getPagerHtml(); ?>
<?php else: ?>
    <div class="message info empty"><span><?php echo __('There are no active subscriptions.') ?></span></div>
<?php endif ?>

